services:
  - type: web
    name: surftheturf
    env: python
    plan: free
    buildCommand: bash ./build.sh
    startCommand: gunicorn surftheturf.wsgi:application
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DJANGO_SETTINGS_MODULE
        value: surftheturf.settings
      - key: DEBUG
        value: "False"

