# Generated by Django 3.2.8 on 2025-10-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('week', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TurfBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('selected_date', models.CharField(max_length=200)),
                ('current_date', models.CharField(max_length=200)),
                ('booking_time', models.CharField(default='', max_length=200)),
                ('slots', models.JSONField(default=list)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='turfBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=12)),
                ('isBooked', models.BooleanField(default=False)),
                ('days', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
