# Generated by Django 3.2.8 on 2025-10-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
    ]
