# Generated by Django 3.2.8 on 2025-10-14 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turf', '0002_auto_20251015_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('business_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('kothrud', 'Kothrud'), ('baner', 'Baner'), ('wakad', 'Wakad'), ('hinjewadi', 'Hinjewadi'), ('viman_nagar', 'Viman Nagar'), ('koregaon_park', 'Koregaon Park'), ('magarpatta', 'Magarpatta'), ('aundh', 'Aundh'), ('hadapsar', 'Hadapsar'), ('kharadi', 'Kharadi'), ('wagholi', 'Wagholi'), ('katraj', 'Katraj'), ('warje', 'Warje'), ('karve_nagar', 'Karve Nagar'), ('deccan', 'Deccan'), ('shivajinagar', 'Shivajinagar'), ('camp', 'Camp'), ('undri', 'Undri'), ('kondhwa', 'Kondhwa'), ('bibvewadi', 'Bibvewadi')], max_length=50)),
                ('address', models.TextField()),
                ('sports_available', models.CharField(help_text='Comma-separated sports (e.g., Cricket, Football(7v7))', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=700.0, max_digits=10)),
                ('has_parking', models.BooleanField(default=True)),
                ('has_washroom', models.BooleanField(default=True)),
                ('has_floodlights', models.BooleanField(default=True)),
                ('has_drinking_water', models.BooleanField(default=True)),
                ('has_changing_room', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('map_link', models.URLField(blank=True, help_text='Google Maps link')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='turf_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='turf_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='turf_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to='turf.turfowner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
