# Generated by Django 3.2.8 on 2025-10-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_turf_turfowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTurfBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_date', models.DateField()),
                ('current_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('slots', models.JSONField()),
                ('payment_id', models.CharField(max_length=200)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='turf.turf')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
